services:
  # PHP Service
  pet-api:
    build:
      context: ..
      dockerfile: .docker/php/Dockerfile
    container_name: pet-api
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      pet_net:
        ipv4_address: 172.28.0.10
    depends_on:
      - pet-mysql

  # Nginx Service
  pet-nginx:
    image: nginx:1.24.0-alpine
    container_name: pet-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      pet_net:
        ipv4_address: 172.28.0.20
    depends_on:
      - pet-api

  # MySQL Service
  pet-mysql:
    image: mysql:8.0
    container_name: pet-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pet
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      pet_net:
        ipv4_address: 172.28.0.30
    ports:
      - "3306:3306"

  # phpMyAdmin Service
  pet-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pet-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: pet-mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      pet_net:
        ipv4_address: 172.28.0.40
    depends_on:
      - pet-mysql

networks:
  pet_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  mysql-data:
    driver: local
